### ISSUE TITLE
[Meshery Server] Panic during Cypress test

### ISSUE THREAD

**Issue by leecalcote** [layer5labs/meshery-extensions-packages#21]
**Description**
Cypress test step:
  1) Login
       Visit MeshMap Designer:

Causes Meshery Server panic.

![Login -- Visit MeshMap Designer (failed)](https://user-images.githubusercontent.com/7570704/179225207-94f1a84a-b524-49ef-a617-1f58dae3422a.png)

https://user-images.githubusercontent.com/7570704/179225218-a89e4634-0825-43fc-9427-da517b3c6ca1.mp4

**Meshery Server Panic**
```
INFO[1889] session not found
server.go:3160: http: panic serving 127.0.0.1:60425: runtime error: invalid memory address or nil pointer dereference
goroutine 1839 [running]:
net/http.(*conn).serve.func1()
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:1802 +0xb9
panic({0x6776220, 0x8ab06e0})
	/Users/lee/sdk/go1.17.8/src/runtime/panic.go:1047 +0x266
github.com/layer5io/meshery/models.(*RemoteProvider).fetchUserDetails(0xc000ae5860, {0xc007a8b07a, 0x0})
	/Users/lee/code/meshery/models/remote_provider.go:278 +0x331
github.com/layer5io/meshery/models.(*RemoteProvider).GetUserDetails(0xc00528af00, 0x6ba4760)
	/Users/lee/code/meshery/models/remote_provider.go:317 +0x35
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1({0x7097280, 0xc0008feb60}, 0xc001480900)
	/Users/lee/code/meshery/handlers/middlewares.go:196 +0x1ba
net/http.HandlerFunc.ServeHTTP(0xc00528af00, {0x7097280, 0xc0008feb60}, 0x1148c728)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2047 +0x2f
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1({0x7097280, 0xc0008feb60}, 0xc001480900)
	/Users/lee/code/meshery/handlers/middlewares.go:72 +0x173
net/http.HandlerFunc.ServeHTTP(0x70b4308, {0x7097280, 0xc0008feb60}, 0x7021560)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2047 +0x2f
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1({0x7097280, 0xc0008feb60}, 0xc001480800)
	/Users/lee/code/meshery/handlers/middlewares.go:40 +0x376
net/http.HandlerFunc.ServeHTTP(0xc001480700, {0x7097280, 0xc0008feb60}, 0xc005c8d9f8)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000f943c0, {0x7097280, 0xc0008feb60}, 0xc001468400)
	/Users/lee/code/go/bin/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc005319920}, {0x7097280, 0xc0008feb60}, 0xc001468400)
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc001144be0, {0x70b4308, 0xc0004f6a50})
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/Users/lee/sdk/go1.17.8/src/net/http/server.go:3034 +0x4e8
```
[Optional] **Additional Context**

**Comment by Chadha93** [comment]
@leecalcote This is no more a case. We can safely close the issue.
